### ISSUE TITLE
Unable to save files

### ISSUE THREAD

**Issue by thijsdekkers** [hmmh/atom-multifile-rename#2]
[Enter steps to reproduce below:]

1. Install multifile-rename package
2. Try to rename multiple files

Atom Version: 1.15.0
OS Name: Microsoft Windows 10 Pro , Version 10.0.14393, Build 14393

When renaming multiple files and pressing 'enter' to save, nothing seems to happen.

**Comment by kreativ-los** [comment]
Thanks for reporting and sorry for the late response.
With the latest patch it should work on Windows.
